package com.rikim.donation.entity;

import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class DonationTest {

    @Test
    public void whenConstructingDonation_thenTheIdShouldConsistOfThreeChars() {
        // Given

        // When
        String autoGeneratedId = new Donation(123L, "x-room-id", 100, 1).getId();

        // Then
        assertThat(autoGeneratedId).hasSize(3);
    }
}